version: '3'

services:
 web:
  container_name: serveur-web
  image: nginx
  ports:
   - 8000:80
  networks:
   - front-web
 db:
  container_name: serveur-db
  image: mysql
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=root
  networks:
   - back-web
 ping:
  build: .
  networks:
   - front-web
   - back-web
networks:
 front-web:
  driver: bridge
  ipam:
   config:
    - subnet: 172.20.0.0/24
 back-web:
  driver: bridge
  ipam:
   config:
    - subnet: 172.21.0.0/24
